#!/bin/bash

wd="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
target_dir=${target_dir:-"$HOME"}
files=(".vimrc" ".vim")

function show_help
{
  echo "
$0 [-f]
Install the following files to $target_dir: ${files[*]}
Options:
-f: Remove existing target file
  "
}

while getopts "fh" opt; do
  case $opt in
    f ) force=1 ;;
    h ) show_help && exit ;;
    ? ) show_help && exit 1 ;;
  esac
done
shift $(($OPTIND - 1))

for f in "${files[@]}"; do
  if [[ -a "$target_dir/$f" ]]; then
    if [[ "$force" = "" ]]; then
      echo "$target_dir/$f already exists! Remove it before installation or run with option '-f'."
      exit 1
    else
      rm -rf "$target_dir/$f"
    fi
  fi
done

ln -sf "$wd/vimrc" "$target_dir"/.vimrc

mkdir "$target_dir"/.vim
cd "$wd"
for f in vim/*; do
  ln -s "$wd/$f" "$target_dir"/.vim/"${f#vim/}"
done
