#!/bin/bash

wd="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

target_dir=${target_dir:-"$HOME"}
files=(".vimrc" ".vim")

if [ -f "$wd/../install.base" ]; then
  . "$wd/../install.base"

  # NOTE: process_cmd_line requires the following global variables:
  #   * target_dir
  #   * files
  # The requirment is due to Bash's limitation on passing array variables.
  process_cmd_line "$@"
fi

echo "Installing $target_dir/.vimrc"
ln -s "$wd/vimrc" "$target_dir"/.vimrc

echo "Installing $target_dir/.vim"
mkdir "$target_dir"/.vim
cd "$wd"
for f in vim/*; do
  ln -s "$wd/$f" "$target_dir"/.vim/"${f#vim/}"
done
